numerical_grid_generation: numerical_grid_generation.cpp
	g++ -std=c++11 -g -O3 numerical_grid_generation.cpp -o numerical_grid_generation
clean:
	rm numerical_grid_generation
run: numerical_grid_generation
	./numerical_grid_generation
